# Generated by Django 3.1.5 on 2021-07-08 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(db_column='command', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('deleted', models.BooleanField(db_column='deleted', default=False)),
            ],
            options={
                'db_table': 'tb_command',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(db_column='caseid', max_length=255)),
                ('mode', models.CharField(db_column='mode', max_length=255)),
                ('interval_bat_s', models.FloatField(db_column='interval_bat_s')),
                ('interval_sending_h', models.FloatField(db_column='interval_sending_h')),
                ('deleted', models.BooleanField(db_column='deleted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_device',
            },
        ),
        migrations.CreateModel(
            name='Measured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_latitude', models.FloatField(db_column='latitude')),
                ('location_longitude', models.FloatField(db_column='longitude')),
                ('source', models.CharField(db_column='source', max_length=255)),
                ('soc', models.FloatField(db_column='soc')),
                ('time', models.DateTimeField(auto_now=True, db_column='time')),
                ('device_id', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='measureds', to='monitor_engine.device')),
            ],
            options={
                'db_table': 'tb_measured',
            },
        ),
    ]
