# Generated by Django 3.1.5 on 2021-07-08 09:18

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_by',
            field=models.IntegerField(db_column='created_by', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeviceTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_column='time')),
                ('isTrack', models.BooleanField(db_column='isTrack')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_engine.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_device_tracking',
            },
        ),
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_column='time')),
                ('mode', models.CharField(db_column='mode', max_length=100)),
                ('interval_bat', models.IntegerField(db_column='interval_bat')),
                ('interval_send', models.IntegerField(db_column='interval_send')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_engine.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
