# Generated by Django 3.1.5 on 2021-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0002_auto_20210708_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.IntegerField(db_column='created_by', default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', default=0),
        ),
    ]
