# Generated by Django 3.1.5 on 2021-07-14 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor_engine', '0005_auto_20210708_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measured',
            old_name='location_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='measured',
            old_name='location_longitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='devicetracking',
            name='device_id',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='monitor_engine.device'),
        ),
        migrations.AlterField(
            model_name='devicetracking',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
