# Generated by Django 3.1.5 on 2021-07-15 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor_engine', '0006_auto_20210714_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='device_id',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='monitor_engine.device'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='commandhistory',
            table='tb_command_history',
        ),
    ]
