# Generated by Django 3.1.5 on 2021-07-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0008_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(db_column='language', default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='level_four',
            field=models.CharField(db_column='level_four', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='level_three',
            field=models.CharField(db_column='level_three', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='level_two',
            field=models.CharField(db_column='level_two', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='levele_one',
            field=models.CharField(db_column='level_one', max_length=50, null=True),
        ),
    ]
