# Generated by Django 3.1.5 on 2021-07-19 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor_engine', '0010_userpreference_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='levele_one',
            new_name='level_one',
        ),
        migrations.RemoveField(
            model_name='measured',
            name='source',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(db_column='notification', max_length=500)),
                ('status', models.BooleanField(db_column='status', default=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('device_id', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='monitor_engine.device')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_notification',
            },
        ),
    ]
