# Generated by Django 3.1.5 on 2021-07-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0011_auto_20210719_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='caseid',
            field=models.CharField(db_column='caseid', default=0, max_length=100),
            preserve_default=False,
        ),
    ]
