# Generated by Django 3.1.5 on 2021-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0012_notification_caseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='interval_bat',
            field=models.IntegerField(db_column='interval_bat', null=True),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='interval_send',
            field=models.IntegerField(db_column='interval_send', null=True),
        ),
    ]
