# Generated by Django 3.1.5 on 2021-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0013_auto_20210723_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='interval_bat',
            field=models.IntegerField(db_column='interval_bat', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='interval_send',
            field=models.IntegerField(db_column='interval_send', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='interval_bat_s',
            field=models.FloatField(db_column='interval_bat_s', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='interval_sending_h',
            field=models.FloatField(db_column='interval_sending_h', null=True),
        ),
    ]
