# Generated by Django 3.1.5 on 2021-07-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0014_auto_20210723_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='total_capacity',
            field=models.IntegerField(db_column='total_capacity', null=True),
        ),
    ]
