# Generated by Django 3.1.5 on 2021-07-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0015_device_total_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='total_capacity',
            field=models.IntegerField(db_column='total_capacity', default=0, null=True),
        ),
    ]
