# Generated by Django 3.1.5 on 2021-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_engine', '0016_auto_20210726_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='measured',
            name='autonomy',
            field=models.CharField(db_column='autonomy', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
